language: python
# python versions
python:
  - "3.7"
# architecture
arch:
  - arm64
env:
- IMGNAME=docker image build -t gitscore docker-files/web/
services:
  - docker
before_install:
  - docker image build -t ${IMGNAME}
# install requirements
install:
  - pip install -r requirements/local.txt
# To run tests
script:
  - flake8
  - coverage run manage.py test apps/repocheck/
# send coverage report to coveralls
after_success:
  coveralls