language: python
# python versions
python:
  - "3.7"
# install requirements
install:
  - pip install -r requirements/local.txt
# To run tests
script:
  - flake8
  - coverage run --source=repocheck test
# send coverage report to coveralls
after_success:
  coveralls