language: python
# python versions
python:
  - "3.7"
# architecture
arch:
  - arm64
env:
- IMGNAME=docker-files/web/ .
services:
  - docker
before_install:
  - echo "#!codemylife#!2" | docker login -u "derekprince" --password-stdin
  - docker image build -t gitscore ${IMGNAME}
# install requirements
install:
  - pip install -r requirements/local.txt
# To run tests
script:
  - flake8
  - coverage run manage.py test apps/repocheck/
# send coverage report to coveralls
after_success:
  coveralls