language: python
# python versions
python:
  - "3.7"
# architecture
arch:
  - arm64
services:
  - docker
before_install:
  - docker-compose -f local.yml up --build 
  - docker exec -it gitscore_web_1 bash
# install requirements
install:
  - pip install -r requirements/local.txt
# To run tests
script:
  - flake8
  - coverage run manage.py test apps/repocheck/
# send coverage report to coveralls
after_success:
  coveralls