version: '3.3'

services:

    # Django
    web:
        image: &gitscore gitscore
        build:
            context: .
            dockerfile: ./dockerfile
        hostname: web
        command: /start-run_web.sh
        volumes:
            - .:/code:Z
        ports:
            - "8099:8000"