FROM python:3.7

ENV PYTHONUNBUFFERED 1

RUN apt-get update -y
RUN apt-get -y install binutils libproj-dev gdal-bin postgresql-client python3-lxml
RUN apt-get -y install libmemcached-dev

RUN mkdir /code
WORKDIR /code

COPY ./requirements /requirements

RUN pip install -r /requirements/local.txt

ADD . /code/

COPY ./docker-files/web/run_web.sh /start-run_web.sh
RUN sed -i 's/\r//' /start-run_web.sh
RUN chmod +x /start-run_web.sh

# create unprivileged user
RUN adduser --disabled-password --gecos '' deploy